// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niwhcvzhvjqrqhyayarv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pd2hjdnpodmpxcnFoeWF5YXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODEwMjUsImV4cCI6MjA3MTM1NzAyNX0.xCaRllWMfp0QseBX1BcGOyvuYNdzxeE0ad6ulRFNRTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});